// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmiBJAwP9mjSB52hhshshAejdzu-FDjRs',
    appId: '1:1023293077169:web:936e99e415509701799490',
    messagingSenderId: '1023293077169',
    projectId: 'todo-list-da05a',
    authDomain: 'todo-list-da05a.firebaseapp.com',
    storageBucket: 'todo-list-da05a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqA-uNs7CbhYV2oL_fN15LHvZVtObjXT0',
    appId: '1:1023293077169:android:da5bca2f6e27271e799490',
    messagingSenderId: '1023293077169',
    projectId: 'todo-list-da05a',
    storageBucket: 'todo-list-da05a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi08DjA-tFLceW0j2w7Tc8jW58kN_Clt0',
    appId: '1:1023293077169:ios:2a1158178b4d5449799490',
    messagingSenderId: '1023293077169',
    projectId: 'todo-list-da05a',
    storageBucket: 'todo-list-da05a.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi08DjA-tFLceW0j2w7Tc8jW58kN_Clt0',
    appId: '1:1023293077169:ios:2a1158178b4d5449799490',
    messagingSenderId: '1023293077169',
    projectId: 'todo-list-da05a',
    storageBucket: 'todo-list-da05a.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmiBJAwP9mjSB52hhshshAejdzu-FDjRs',
    appId: '1:1023293077169:web:73f5d8e63c1c9cc7799490',
    messagingSenderId: '1023293077169',
    projectId: 'todo-list-da05a',
    authDomain: 'todo-list-da05a.firebaseapp.com',
    storageBucket: 'todo-list-da05a.appspot.com',
  );

}